spring.application.name=core-service
server.port=8996
# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/user
spring.datasource.username=postgres
spring.datasource.password=Pgadmin@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true